// <auto-generated />
using System;
using EmlakTakip.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmlakTakip.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20250602083244_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmlakTakip.Models.Emlak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BalkonVarMi")
                        .HasColumnType("bit");

                    b.Property<int>("BanyoSayisi")
                        .HasColumnType("int");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BinaYasi")
                        .HasColumnType("int");

                    b.Property<double?>("Boylam")
                        .HasColumnType("float");

                    b.Property<int>("BulunduguKat")
                        .HasColumnType("int");

                    b.Property<double?>("Enlem")
                        .HasColumnType("float");

                    b.Property<bool>("EsyaliMi")
                        .HasColumnType("bit");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GorselYolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IlanTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IlanTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsitmaTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KatSayisi")
                        .HasColumnType("int");

                    b.Property<bool>("KrediliMi")
                        .HasColumnType("bit");

                    b.Property<int>("Metrekare")
                        .HasColumnType("int");

                    b.Property<string>("OdaSayisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SiteIciMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Emlaklar");
                });

            modelBuilder.Entity("EmlakTakip.Models.EmlakFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmlakId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmlakId");

                    b.ToTable("EmlakFotolar");
                });

            modelBuilder.Entity("EmlakTakip.Models.EmlakFoto", b =>
                {
                    b.HasOne("EmlakTakip.Models.Emlak", "Emlak")
                        .WithMany()
                        .HasForeignKey("EmlakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emlak");
                });
#pragma warning restore 612, 618
        }
    }
}
